version: "3"
services:
  credito-api:
    image: credito-api
    build: 
      context: ../credito-api
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/credito_db?serverTimezone=UTC
    networks:
      - springmysql-net
    depends_on:
      - mysqldb

#  seguro-api:
#    image: seguro-api
#    build: 
#      context: ../credito-api
#      dockerfile: Dockerfile
#    ports:
#      - "8082:8082"
#    environment:
#      - spring.datasource.url=jdbc:mysql://mysqldb:3306/seguro_db?serverTimezone=UTC
#    networks:
#      - springmysql-net
#    depends_on:
#      - mysqldb

  mysqldb:
    image: mysql:latest
    networks:
      - springmysql-net
    environment:
      - MYSQL_ROOT_PASSWORD=rm344810db@
      - MYSQL_DATABASE=credito_db

networks:
  springmysql-net: